version: '3.7'

x-web-template: &template
  user: root
  tty: true
  environment:
    TZ: "Asia/Tokyo"
  image: prom/node-exporter:v1.0.0-rc.0
  volumes:
    - /proc:/host/proc
    - /sys:/host/sys
    - /:/rootfs

services:
  grafana:
    container_name: grafana001
    image: grafana/grafana:6.6.2
    volumes:
      - data-grafana:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus001
    ports:
      - 9090:9090
    volumes:
      - data-prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  node-exporter001:
    container_name: node-exporter001
    <<: *template

  node-exporter002:
    container_name: node-exporter002
    <<: *template

  blackbox_exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml

  nginx:
    build: ./nginx
    container_name: nginx.dev.com
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/ssl.conf:/etc/nginx/conf.d/ssl.conf
    dns:
      - 8.8.8.8
      - 9.9.9.9

  webapp:
    build: ./webapp
    container_name: sample.web.com
    volumes:
      - ./webapp/main.py:/app/main.py

volumes:
  data-prometheus:
    driver: local
  data-grafana:
    driver: local
